version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/maxLiveDB
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
