version: '3.9'
services:
  backend:
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - 5050:5050
    container_name: maxlive-backend
    networks:
      - maxlive-network
    volumes:
      - ./:/app
    restart: on-failure
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://maxlive:AsqQkL8%3CH6L_rS@mongo:27017
      # AUTH
      AUTH_SECRET_KEY: 12345678

    depends_on:
      - mongo
  mongo:
    container_name: maxlive-db
    image: mongo
    ports:
      - 27177:27017
    networks:
      - maxlive-network
    volumes:
      - maxliveDBdata:/data/db
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: maxlive
      MONGO_INITDB_ROOT_PASSWORD: AsqQkL8<H6L_rS
      MONGO_INITDB_DATABASE: maxlivePROD

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - maxlive-network
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: maxliveDBAdmin
      ME_CONFIG_BASICAUTH_PASSWORD: b}wu.gk3k?(~MNsL
      ME_CONFIG_MONGODB_ADMINUSERNAME: maxlive
      ME_CONFIG_MONGODB_ADMINPASSWORD: AsqQkL8<H6L_rS
      ME_CONFIG_MONGODB_URL: mongodb://maxlive:AsqQkL8<H6L_rS@mongo:27017/maxlivePROD?authSource=admin
    depends_on:
      - mongo
networks:
  maxlive-network:
volumes:
  maxliveDBdata:
