version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      MONGODB_URI: "mongodb://syscoadmin:E7Dw~e5NKh4Ly%27s@mongo:27017/maxProd?authSource=admin"
      AUTH_SECRET_KEY: SecretKey123456789
      EMAIL_PASS: myaa trfs ymcq msja
      BASE_API_URL: https://max.syscomatic.com/api/v1

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
